# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
        project: [django-filter, django-grappelli, django-guardian, django-hijack, django-sql-explorer, django-tables2]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: setup-project
      run: python setup.py develop
      working-directory: targets/${{ matrix.project }}
    - name: scan
      uses: tonybaloney/pycharm-security@dev-actions
      with:
        path: .
        source: targets/${{ matrix.project }}
        requirements: targets/${{ matrix.project }}/requirements.txt
    - uses: actions/upload-artifact@v2
      name: results
      with:
        name: ${{ matrix.project }}-results
        path: out/
